### ISSUE TITLE
Cannot invoke error.

### ISSUE THREAD

**Issue by Bitr0t-Zygzz** [RuscalWorld/FabricExporter#1] opened 2021-06-25 02:17 UTC
I am trying to configure fabric exporter for 1.16.5 
using, Windows with all of fabric 3 mod pack.

Not sure if I can ignore the error as I still haven't gotten the panel connected yet.

I can upload the entire log if necessary. 

added note: visiting the 25585/metrics seems to work so I feel that this is not of concern
![image](https://user-images.githubusercontent.com/12416643/123358657-691d2980-d59e-11eb-956e-878ecd8a08d2.png)

**Comment by RuscalWorld** [comment] 2021-06-26 08:42
I've tried FabricExporter 1.0.1 and 1.0.3, but was unable to reproduce this with [this modpack](https://www.curseforge.com/minecraft/modpacks/all-of-fabric-3). Please upload the entire log and `config/exporter.properties`

**Comment by LolHens** [comment] 2021-09-06 00:42
I am experiencing the same thing on my server.
I think that I might have found the cause in [MillisPerTick.java#L16](https://github.com/RuscalWorld/FabricExporter/blob/master/src/main/java/ru/ruscalworld/fabricexporter/metrics/MillisPerTick.java#L16) because for the value for the label "type" is undefined.
It only happens when Spark is still initializing.

**Comment by RuscalWorld** [comment] 2021-09-06 18:56
It seems to me that race condition of some kind takes place here, because I still can't reproduce this. I suppose that registering metrics on mod initialization with running updater on server start also can cause this. And I also don't know why this occurs only with `MillisPerTick`, but doesn't occur with `TicksPerSecond` where the similar solution with default gauge values is used.

**Comment by LolHens** [comment] 2021-09-06 22:25
The TicksPerSecond Gauge doesn't have any labels defined so it doesn't need label values but MillisPerTick has the "type" label and doesn't get a value in that null-check case. Maybe instead of setting the gauge to 0 you could set it for the type "min", "max" and "mean".

**Comment by RuscalWorld** [comment] 2021-09-07 19:27
Okay, it looks like this is the real cause of this problem. Now it should be fixed. Thanks for help.

**Closed by RuscalWorld** 2021-09-07 19:27 UTC
